version: '2.1'
services:

  data-broker-redis:
    image: "redis:5.0.5-alpine3.10"

  zookeeper:
    image: "zookeeper:3.4"

  kafka:
    image: "ches/kafka:0.10.1.1"
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_IP: zookeeper

  broker:
    image: "dojot/data-broker"
    depends_on:
      - kafka
